### ISSUE TITLE
[Umbrella Issue] 중간 결과물 개발

### ISSUE THREAD

**Issue by ENvironmentSet** [s-center/kiosk#13]
|   Goal   |   동작하는 서비스 구현    |
|--------|----------------------|
|   Due    |   10/31, 19:00              |

- [ ] 취향 선택 구현 #6 
  * [x] #15
  * [x] #14 
  * [x] 3단 이미지 슬라이드 개발
  * [x] #18
  * [x] 키워드 선택 페이지 개발
  * [x] #21
  * [x] 안내 시퀀스 구현 (피그마 4~6 페이지)
  * [x] #23
- [x] #17
  * [x] 데이터 조합 결과에 맞는 그래픽 띄우기 ( 더미 텍스트) 
  * [x] 하단 버튼 두 개 가져다 쓰기 
  * [x] 상단 로고 컴포넌트 가져다가 넣기
  * [x] 배경 이미지 삽입
  * [x] QR 생성 및 제시 페이지 구현

- [ ] 제품 추천 구현
  * [x] 이미지 확대 축소 반복 구현
  * [x] 이미지 클릭 시 알맞는 제품 나오는 페이지 구현
  * [ ] My cart
  * [ ] 결제 페이지
  * [x] 영수증

----

Non-goal: UI 요소의 정확한 수치 확정, 실제 데이터/에셋 사용

**Comment by ENvironmentSet** [comment]
@kong33 

조향 결과 페이지 구현 시 어떤 기능들이 필요한지 시간 나실 때 적어주세요!
